#!/bin/bash

set -e -u

touch additional_tags

case $GITHUB_REF in
  refs/heads/*)
    tag=$(echo $GITHUB_REF | sed 's|refs/heads/||')
    ;;

  refs/tags/v[0-9]*)
    tag=latest
    version=$(echo $GITHUB_REF | sed 's|refs/tags/v||')

    {
      echo $version | cut -d. -f1
      echo $version | cut -d. -f1,2
      echo $version | cut -d. -f1,2,3
    } | uniq >> additional_tags

    ;;

  refs/tags/*)
    tag=$(echo $GITHUB_REF | sed 's|refs/tags/||')
    ;;

  refs/pull/[0-9]*/merge)
    tag=pr$(echo $GITHUB_REF | sed 's|refs/pull/\([0-9]\+\)/merge|\1|')
    ;;

  *)
    tag=$GITHUB_SHA
    ;;
esac

exec /opt/resource/out . <<EOF
{
  "source": {
    "repository": "vito/oci-build-task",
    "tag": "$tag",
    "username": "$DOCKER_USERNAME",
    "password": "$DOCKER_PASSWORD"
  },
  "params": {
    "image": "./image/image.tar",
    "additional_tags": "./additional_tags"
  }
}
EOF
