name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: {submodules: true}
    - run: scripts/test

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: {submodules: true}
    - run: scripts/build
    - run: scripts/build-image
    - uses: actions/upload-artifact@v4
      with:
        name: image
        path: image

  push-image:
    needs: [build-image]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: image
        path: image
    - uses: docker://concourse/registry-image-resource
      with: {entrypoint: scripts/push-image}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
